name: Parsing Automation CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Run Smoke Tests
        run: mvn test -DsuiteXmlFile=testng/smoke.xml
        env:
          DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
          PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
          DEV_URL: ${{ secrets.DEV_URL }}
          PROD_URL: ${{ secrets.PROD_URL }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
